apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "roster.fullname" . }}-config
  labels: {{- include "roster.labels" . | nindent 4 }}
data:
  config.yml: |-
{{ .Values.config.yaml | indent 4 }}
