package undercover

import (
	"strings"
	"testing"
)

func TestRedact_StripsAnthropicReferences(t *testing.T) {
	cases := []string{
		"Powered by Anthropic API.",
		"This product uses Anthropic, PBC's models.",
		"contact Anthropic Inc. for licensing",
		"anthropic",
	}
	for _, in := range cases {
		out := Redact(in)
		if strings.Contains(strings.ToLower(out), "anthropic") {
			t.Errorf("Redact(%q) = %q — still mentions vendor", in, out)
		}
	}
}

func TestRedact_StripsModelIdentifiers(t *testing.T) {
	cases := map[string]string{
		"Generated with claude-haiku-4-5-20251001 in 1.2s": "Generated with  in 1.2s",
		"Switching from claude-sonnet-4-6 to claude-opus-4-7.": "Switching from  to .",
	}
	for in, want := range cases {
		if got := Redact(in); got != want {
			t.Errorf("Redact(%q):\n got  %q\n want %q", in, got, want)
		}
	}
}

func TestRedact_LeavesGenericClaudeWordAlone(t *testing.T) {
	// "Claude API" inside a sentence is borderline — but we shouldn't
	// blank single-word "Claude" because it appears in legitimate places
	// (e.g. "the Claude side of the codebase"). Only versioned model
	// strings and explicit Anthropic mentions get scrubbed.
	out := Redact("We named the assistant Claude after a coworker.")
	if !strings.Contains(out, "Claude") {
		t.Errorf("plain 'Claude' should survive, got: %q", out)
	}
}

func TestRedact_StripsAIDisclaimers(t *testing.T) {
	cases := map[string]string{
		"As an AI assistant, I cannot recommend that.":   "I cannot recommend that.",
		"As an AI language model, here's my take:":       "here's my take:",
		"I'm an AI, but here's what I think.":            "but here's what I think.",
		"As a large language model, I have no opinions.": "I have no opinions.",
	}
	for in, want := range cases {
		got := Redact(in)
		if got != want {
			t.Errorf("Redact(%q):\n got  %q\n want %q", in, got, want)
		}
	}
}

func TestRedact_RewritesGeneratedByPhrase(t *testing.T) {
	cases := []string{
		"Generated by Claude on 2026-05-03.",
		"Generated by AI.",
		"This summary was generated by an AI.",
	}
	for _, in := range cases {
		got := Redact(in)
		if strings.Contains(got, "Generated by") || strings.Contains(got, "generated by") {
			// Only "summarised" should remain; anything starting with
			// "generated by" indicates the rewrite missed.
			t.Errorf("Redact(%q) = %q — phrase not rewritten", in, got)
		}
		if !strings.Contains(got, "summarised") {
			t.Errorf("Redact(%q) = %q — expected 'summarised' replacement", in, got)
		}
	}
}

func TestRedact_BlanksSecretShapedStrings(t *testing.T) {
	cases := []struct {
		in     string
		marker string
	}{
		{"export ANTHROPIC_API_KEY=sk-ant-abcdEF1234567890_xyz", "[redacted-claude-key]"},
		{"GH_TOKEN=ghp_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "[redacted-github-token]"},
		{"slack token: xoxp-1234567890-abcdef-XYZ", "[redacted-slack-token]"},
	}
	for _, tc := range cases {
		got := Redact(tc.in)
		if !strings.Contains(got, tc.marker) {
			t.Errorf("Redact(%q) = %q — missing marker %q", tc.in, got, tc.marker)
		}
		if strings.Contains(got, "sk-ant-abcdEF") || strings.Contains(got, "ghp_aaaa") || strings.Contains(got, "xoxp-1234") {
			t.Errorf("Redact(%q) = %q — secret leaked through", tc.in, got)
		}
	}
}

func TestRedact_Idempotent(t *testing.T) {
	in := "Generated by Claude (claude-sonnet-4-6) for Anthropic, PBC. As an AI assistant, here goes."
	once := Redact(in)
	twice := Redact(once)
	if once != twice {
		t.Errorf("Redact not idempotent:\n once: %q\n twice: %q", once, twice)
	}
}

func TestRedactAll_InPlace(t *testing.T) {
	items := []string{
		"good text",
		"contains Anthropic reference",
		"another good one",
	}
	RedactAll(items)
	if items[0] != "good text" || items[2] != "another good one" {
		t.Errorf("clean text disturbed: %v", items)
	}
	if strings.Contains(items[1], "Anthropic") {
		t.Errorf("dirty text not scrubbed: %v", items)
	}
}

func TestSystemSuffix_HasKeyDirectives(t *testing.T) {
	for _, want := range []string{"AI", "Claude", "vendor", "human teammate"} {
		if !strings.Contains(SystemSuffix, want) {
			t.Errorf("SystemSuffix should mention %q", want)
		}
	}
}
