// Package undercover enforces the "virtual employee" persona: every text
// Roster posts to GitHub / Jira / Confluence / Slack on behalf of the
// virtual account is treated as if a real human teammate wrote it.
//
// Two layers, both applied:
//
//  1. SystemSuffix is appended to every Claude-driven module's system
//     prompt. It tells the model not to identify itself as an AI, name
//     a vendor, or hedge with disclaimer phrases. (The cheapest layer:
//     a well-instructed model rarely says the forbidden things.)
//
//  2. Redact runs as a final scrub on every outbound text just before
//     it leaves the process. It catches the AI's leaks, but also the
//     legitimate-but-sensitive things (API key shaped strings, model
//     identifiers, vendor references) that may have come from somewhere
//     else (e.g. a GH commit message Module D is summarising).
//
// Belt and suspenders: layer 1 is the bulk of the protection, layer 2
// is the safety net.
package undercover

import "regexp"

// SystemSuffix gets appended verbatim to every AI module's system prompt.
const SystemSuffix = `

UNDERCOVER MODE: You are writing on behalf of a human teammate. Do NOT
identify yourself as an AI, a bot, an assistant, an LLM, or "Claude".
Do NOT mention that the output was generated by an AI. Do NOT name the
model or vendor. Do NOT add disclaimers like "I cannot ..." or "As a
language model ...". Write as a colleague — concise, factual, no
boilerplate.`

// scrubber pairs a pattern with the replacement to use when matched.
type scrubber struct {
	re      *regexp.Regexp
	replace string
}

// scrubbers run in order. First, secrets get blanked with explicit
// markers (so reading audit logs makes it obvious something tried to
// leak). Then brand / AI-disclaimer giveaways get *quietly* stripped
// — surfacing "[redacted]" in a Jira ticket would itself blow the cover.
var scrubbers = []scrubber{
	// ── Secret-shaped strings ────────────────────────────────────
	// Anthropic API keys.
	{regexp.MustCompile(`\bsk-ant-[A-Za-z0-9_-]+`), "[redacted-claude-key]"},
	// GitHub PATs (classic + fine-grained + app-installation).
	{regexp.MustCompile(`\b(ghp|gho|ghu|ghs|github_pat)_[A-Za-z0-9_]{20,}`), "[redacted-github-token]"},
	// Slack tokens (user / bot / config).
	{regexp.MustCompile(`\bxox[abporsf]-[A-Za-z0-9-]{10,}`), "[redacted-slack-token]"},
	// Atlassian API tokens are 24-char base64ish — too risky to regex
	// without false positives. Counted on operators not pasting them
	// into issue bodies.

	// ── Vendor / model identifiers ───────────────────────────────
	// "Anthropic, PBC" / "Anthropic Inc" / "Anthropic API" / lone "Anthropic".
	{regexp.MustCompile(`(?i)\bAnthropic(\s*,?\s*(PBC|Inc\.?|API))?\b`), ""},
	// Versioned Claude models — claude-opus-4-7, claude-sonnet-4-6-20250514, etc.
	{regexp.MustCompile(`(?i)\bclaude-(opus|sonnet|haiku)-[\w.-]*\b`), ""},

	// ── AI-disclaimer giveaways ──────────────────────────────────
	// "As an AI assistant," / "As an AI language model,"
	{regexp.MustCompile(`(?i)\bAs an AI(\s+(assistant|language model|model))?\s*[,:]?\s*`), ""},
	// "I'm an AI" / "I am an AI"
	{regexp.MustCompile(`(?i)\bI\s*'?\s*(m|am)\s+an\s+AI\b[,. ]*`), ""},
	// "Generated by Claude" / "Generated by an AI" → softer wording.
	{regexp.MustCompile(`(?i)\bgenerated by (Claude|an AI|AI)\b`), "summarised"},
	// "as a large language model"
	{regexp.MustCompile(`(?i)\bas a large language model\b[,. ]*`), ""},
}

// Redact returns text with every scrubber applied. Idempotent.
func Redact(text string) string {
	for _, s := range scrubbers {
		text = s.re.ReplaceAllString(text, s.replace)
	}
	return text
}

// RedactAll applies Redact to every element of a string slice in place.
// Convenient for redacting comment bodies / pull-request review snippets.
func RedactAll(items []string) {
	for i := range items {
		items[i] = Redact(items[i])
	}
}
