package poller

import (
	"context"
	"fmt"
	"log"
	"time"

	gh "github.com/45online/roster/internal/adapters/github"
)

// Handler processes a single, filtered, dedup'd event. It is invoked
// synchronously by the poller in event-creation order (oldest first).
type Handler func(ctx context.Context, ev gh.Event) error

// Config configures a Poller.
type Config struct {
	// GH is the GitHub client to use. Required.
	GH *gh.Client
	// Repo is "owner/name". Required.
	Repo string
	// Interval is the polling cadence. Defaults to 30s. Will be raised to
	// the value GitHub returns in X-Poll-Interval if larger.
	Interval time.Duration
	// SelfLogin is the login of the virtual employee Roster operates as.
	// Events authored by this login are dropped (anti-loop). Required.
	SelfLogin string
	// BaseDir is where cursor state is stored. Defaults to "$HOME/.roster".
	BaseDir string
	// Handler is invoked for each event that passes filtering. Required.
	Handler Handler
	// Logger is optional; defaults to the standard log package.
	Logger *log.Logger
}

// Poller polls a single repository for events and dispatches them to a Handler.
type Poller struct {
	cfg    Config
	cursor *Cursor
	logger *log.Logger
}

// New constructs a Poller, loading (or creating) its persistent cursor.
func New(cfg Config) (*Poller, error) {
	if cfg.GH == nil {
		return nil, fmt.Errorf("poller: GH client is required")
	}
	if cfg.Repo == "" {
		return nil, fmt.Errorf("poller: Repo is required")
	}
	if cfg.SelfLogin == "" {
		return nil, fmt.Errorf("poller: SelfLogin is required (anti-loop)")
	}
	if cfg.Handler == nil {
		return nil, fmt.Errorf("poller: Handler is required")
	}
	if cfg.Interval == 0 {
		cfg.Interval = 30 * time.Second
	}
	if cfg.BaseDir == "" {
		cfg.BaseDir = defaultBaseDir()
	}
	if cfg.Logger == nil {
		cfg.Logger = log.Default()
	}

	cur, err := LoadCursor(cfg.BaseDir, cfg.Repo)
	if err != nil {
		return nil, err
	}
	return &Poller{cfg: cfg, cursor: cur, logger: cfg.Logger}, nil
}

// Run starts the polling loop. It blocks until ctx is cancelled.
func (p *Poller) Run(ctx context.Context) error {
	p.logger.Printf("[poller] %s: starting (interval=%s, self=%s, last_event=%s)",
		p.cfg.Repo, p.cfg.Interval, p.cfg.SelfLogin, p.cursor.LastEventID)

	// First tick immediately so the user sees activity without a wait.
	if err := p.pollOnce(ctx); err != nil && ctx.Err() == nil {
		p.logger.Printf("[poller] %s: poll error: %v", p.cfg.Repo, err)
	}

	t := time.NewTicker(p.cfg.Interval)
	defer t.Stop()

	for {
		select {
		case <-ctx.Done():
			p.logger.Printf("[poller] %s: stopping (%v)", p.cfg.Repo, ctx.Err())
			return ctx.Err()
		case <-t.C:
			if err := p.pollOnce(ctx); err != nil && ctx.Err() == nil {
				p.logger.Printf("[poller] %s: poll error: %v", p.cfg.Repo, err)
			}
		}
	}
}

// pollOnce performs one round of: fetch events → filter → dispatch → save cursor.
func (p *Poller) pollOnce(ctx context.Context) error {
	resp, err := p.cfg.GH.ListEvents(ctx, p.cfg.Repo, p.cursor.LastETag)
	if err != nil {
		return err
	}

	// Keep ETag fresh regardless of body presence.
	if resp.ETag != "" {
		p.cursor.LastETag = resp.ETag
	}

	if resp.NotModified || len(resp.Events) == 0 {
		_ = p.cursor.Save()
		return nil
	}

	// Honor GitHub's recommended interval if larger than our config.
	if resp.PollInterval > p.cfg.Interval {
		p.logger.Printf("[poller] %s: server suggests %s interval (we're at %s)",
			p.cfg.Repo, resp.PollInterval, p.cfg.Interval)
	}

	// Events arrive newest-first; we want to process oldest-first so the
	// cursor advances monotonically, and so a downstream module sees them
	// in causal order.
	fresh := freshEventsOldestFirst(resp.Events, p.cursor.LastEventID)

	for _, ev := range fresh {
		if ev.Actor.Login == p.cfg.SelfLogin {
			// Anti-loop: drop events generated by ourselves.
			p.cursor.LastEventID = ev.ID
			continue
		}
		if err := p.cfg.Handler(ctx, ev); err != nil {
			// Log but keep going; advance cursor so we don't re-process.
			p.logger.Printf("[poller] %s: handler error on event %s (%s): %v",
				p.cfg.Repo, ev.ID, ev.Type, err)
		}
		p.cursor.LastEventID = ev.ID
	}

	return p.cursor.Save()
}

// freshEventsOldestFirst returns events with ID > since, in oldest-first
// order. GitHub's events feed is sorted newest-first; we reverse and
// drop already-seen tails.
func freshEventsOldestFirst(events []gh.Event, since string) []gh.Event {
	if len(events) == 0 {
		return nil
	}
	// Find the boundary: the first index whose ID equals `since`.
	cut := len(events)
	if since != "" {
		for i, ev := range events {
			if ev.ID == since {
				cut = i
				break
			}
		}
	}
	// events[0:cut] are strictly newer than `since`; reverse.
	out := make([]gh.Event, 0, cut)
	for i := cut - 1; i >= 0; i-- {
		out = append(out, events[i])
	}
	return out
}
